### ISSUE TITLE
KaguyaTC SCLK error

### ISSUE THREAD

**Issue by jlaura** [DOI-USGS/ale#495]
Once ALESPICEROOT is set (see #494) attempting to generate an ISD for a TC image fails with the following error:

```bash
Trying <class 'ale.drivers.selene_drivers.KaguyaTcPds3NaifSpiceDriver'>
Failed: Failed to find metakernels. mission: selene, year:2008, versions="latest" spice root = "<my_spice_root>"
```
Looking in the kaguyatc folder, I am not seeing any metakernels. I checked the ISIS Data Area on S3 as well, and I'm not seeing metakernels in there either. How is one supposed to load a PDS3 labelled Kaguya TC image?

**Comment by jessemapel** [comment]
We've stopped distributing metakernels with the ISIS data area as it requires several extra steps and checks to properly set them up upon download.

For right now, you will need to use the metakernels supplied in the NAIF archives or generate your own. You can also use the ISIS spiceinit selected kernels.

All of this will ultimately be resolved with SpiceQL.

**Comment by jlaura** [comment]
The Kaguya team does not make metakernels as far as I can tell, so it looks like ISIS is the only viable path. Unfortunately, I am seeing the following attempting to use the ISIS selected kernels in ALE:

```bash
    base_band = band_map[self.label.get("BASE_BAND")]
KeyError: None
Trying <class 'ale.drivers.selene_drivers.KaguyaTcPds3NaifSpiceDriver'>
Failed:
================================================================================

Toolkit version: CSPICE_N0067

SPICE(INVALIDSIZE) --

Offset count 2 does not match field count 1 for SCLK -131.

sct2e_c --> SCT2E --> SCTYPE --> SCTY01 --> ZZSCUP01 --> ZZSCAD01 --> SCLD01

================================================================================
```

code used is:

```python
    kernels = ale.util.generate_kernels_from_cube(cub, expand=True)
    usgscsm_str = ale.loads(cub_file, props={'kernels':kernels}, verbose=True)
```

**Comment by jessemapel** [comment]
That error looks like we're passing the SClock value incorrectly. What image is this?

**Comment by jlaura** [comment]
@jessemapel TC1W2B0_01_01800N340E2398

Though you should be able to [pull any from here](https://data.darts.isas.jaxa.jp/pub/pds3/sln-l-tc-3-w-level2b0-v1.0/20080514/data/) and run kaguyat2isis and spiceinit.

**Comment by jlaura** [comment]
While this is still an issue, the merge of #501 means that a spiceinited ISIS cube can be natively loaded without the need for these gymnastics.
